# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  configure_aws_cli:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Configure AWS Access Key ID
          command: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
      - run:
          name: Configure AWS Secret Access Key
          command: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY 
      - run:
          name: Configure AWS default region
          command: aws configure set region $AWS_DEFAULT_REGION 

  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run: aws s3 ls
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  print_ID:
    jobs:
      - configure_aws_cli 
      - create_infrastructure:
          requires:
          - configure_aws_cli

